### ISSUE TITLE
Blocking call to load_verify_locations causing warnings in Home Assistant

### ISSUE THREAD

**Issue by 4041-6A19** [pypolestar/polestar_api#159]
Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f671a3e50>,) inside the event loop by custom integration 'polestar_api' at custom_components/polestar_api/pypolestar/auth.py, line 24

For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations

Details from log:

2024-10-13 11:22:57.905 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f671a3e50>,) inside the event loop by custom integration 'polestar_api' at custom_components/polestar_api/pypolestar/auth.py, line 24: self._client_session = httpx.AsyncClient() (offender: /usr/local/lib/python3.12/site-packages/httpx/_config.py, line 149: context.load_verify_locations(cafile=cafile)), please report it to the author of the 'polestar_api' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
result = await _async_setup_component(hass, domain, config)
File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component
await asyncio.gather(
File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr>
create_eager_task(
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task
return Task(coro, loop=loop, name=name, eager_start=True)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
await self.async_setup(hass, integration=integration)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/polestar_api/__init__.py", line 42, in async_setup_entry
polestar = Polestar(
File "/config/custom_components/polestar_api/polestar.py", line 28, in __init__
self.polestarApi = PolestarApi(username, password)
File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 31, in __init__
self.auth = PolestarAuth(username, password)
File "/config/custom_components/polestar_api/pypolestar/auth.py", line 24, in __init__
self._client_session = httpx.AsyncClient()

**Comment by jschlyter** [comment]
Fixed in next release
