### ISSUE TITLE
Unexpected error when creating the API -Polestar Account in the web works 

### ISSUE THREAD

**Issue by alexeckh** [pypolestar/polestar_api#190]
Hi,

i had prior installed the integration. After deletion i would install it again.
i got the following error: "Unexpected error when creating the API."
Polestar Account in the web works and shows my car in the web.

Protocol:

Logger: custom_components.polestar_api.config_flow
Quelle: custom_components/polestar_api/config_flow.py:39
Integration: polestar_api (Dokumentation, Probleme)
Erstmals aufgetreten: 16:55:06 (1 Vorkommnisse)
Zuletzt protokolliert: 16:55:06

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 39, in _create_device
    await device.init()
  File "/config/custom_components/polestar_api/polestar.py", line 34, in init
    await self.polestarApi.init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 54, in init
    carData = await self._get_vehicle_data()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 144, in _get_vehicle_data
    result = await self.get_graph_ql(params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 242, in get_graph_ql
    raise PolestarNotAuthorizedException("Unauthorized Exception")
custom_components.polestar_api.pypolestar.exception.PolestarNotAuthorizedException: Unauthorized Exception

**Comment by jschlyter** [comment]
Did you change password for your account?

**Comment by alexeckh** [comment]
No

Am 1. November 2024 09:18:39 MEZ schrieb Jakob Schlyter ***@***.***>:

**Comment by alexeckh** [comment]
Tried 1.6.15: it works, 1.8.x prerelease not

**Comment by alexeckh** [comment]
Now both versions didn’t work.
When I install 1.6.15 I get the message ‚Kein Token in der Antwort gefunden. Bitte überprüfe Deine Anmeldeinformationen.‘
At 1.8.0 ‚API unexpected failure‘

**Comment by alexeckh** [comment]
issue persists 
error message: 'API unexpected failure'

**Comment by jschlyter** [comment]
Are there anything else in the logs from Home Assistant?

**Comment by alexeckh** [comment]
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.polestar_api.config_flow
Quelle: custom_components/polestar_api/config_flow.py:47
Integration: polestar_api (Dokumentation, Probleme)
Erstmals aufgetreten: 15:09:23 (2 Vorkommnisse)
Zuletzt protokolliert: 15:10:02

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 235, in _query_graph_ql
    result = await client.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gql/client.py", line 1639, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'User not authenticated', 'path': ['getConsumerCarsV2'], 'extensions': {'code': 'UNAUTHENTICATED', 'exception': {'stacktrace': ['AuthenticationError: User not authenticated', '    at ayn (/var/task/src/functions/mystar/handler.js:1568:2188838)', '    at uyn (/var/task/src/functions/mystar/handler.js:1568:2190110)', '    at Cr (/var/task/src/functions/mystar/handler.js:1568:2212332)', '    at getConsumerCarsV2 (/var/task/src/functions/mystar/handler.js:1568:2214029)', '    at TFr.r.resolve (/var/task/src/functions/mystar/handler.js:287:6609)', '    at CBe (/var/task/src/functions/mystar/handler.js:83:5200)', '    at kG (/var/task/src/functions/mystar/handler.js:83:4784)', '    at yEr (/var/task/src/functions/mystar/handler.js:83:4308)', '    at IBe (/var/task/src/functions/mystar/handler.js:83:2354)', '    at g (/var/task/src/functions/mystar/handler.js:287:40983)', '    at RUr (/var/task/src/functions/mystar/handler.js:287:40154)', '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)', '    at async TQe (/var/task/src/functions/mystar/handler.js:288:2270)'], 'message': 'User not authenticated', 'locations': [{'line': 1, 'column': 36}], 'path': ['getConsumerCarsV2']}, 'serviceName': 'mystar'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 47, in _create_device
    await device.async_init()
  File "/config/custom_components/polestar_api/polestar.py", line 150, in async_init
    await self.polestar_api.async_init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 69, in async_init
    if not (car_data := await self._get_vehicle_data(verbose=verbose)):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 204, in _get_vehicle_data
    result = await self._query_graph_ql(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 251, in _query_graph_ql
    raise PolestarNotAuthorizedException(
custom_components.polestar_api.pypolestar.exception.PolestarNotAuthorizedException: User not authenticated

**Comment by alexeckh** [comment]
DNS
[INFO] 127.0.0.1:51114 - 30119 "AAAA IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.000239631s
[ERROR] plugin/errors: 2 pc-api.polestar.com. AAAA: dial tcp 1.1.1.1:853: i/o timeout
[INFO] 127.0.0.1:40860 - 10368 "A IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.000278989s
[ERROR] plugin/errors: 2 pc-api.polestar.com. A: dial tcp 1.1.1.1:853: i/o timeout
[INFO] 127.0.0.1:35519 - 56463 "AAAA IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.00100264s
[ERROR] plugin/errors: 2 pc-api.polestar.com. AAAA: dial tcp 1.1.1.1:853: i/o timeout
[INFO] 127.0.0.1:34751 - 10771 "A IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.001007593s
[ERROR] plugin/errors: 2 pc-api.polestar.com. A: dial tcp 1.1.1.1:853: i/o timeout
[INFO] 127.0.0.1:57561 - 51810 "AAAA IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.000898013s
[ERROR] plugin/errors: 2 pc-api.polestar.com. AAAA: dial tcp 1.1.1.1:853: i/o timeout
[INFO] 127.0.0.1:52240 - 18659 "A IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.000841767s
[ERROR] plugin/errors: 2 pc-api.polestar.com. A: dial tcp 1.1.1.1:853: i/o timeout
[INFO] 127.0.0.1:48196 - 59660 "A IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.000760944s
[ERROR] plugin/errors: 2 pc-api.polestar.com. A: dial tcp 1.0.0.1:853: i/o timeout
[INFO] 127.0.0.1:43767 - 63814 "AAAA IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.00085577s
[ERROR] plugin/errors: 2 pc-api.polestar.com. AAAA: dial tcp 1.0.0.1:853: i/o timeout
[INFO] 127.0.0.1:59963 - 25644 "AAAA IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.000937339s
[ERROR] plugin/errors: 2 pc-api.polestar.com. AAAA: dial tcp 1.0.0.1:853: i/o timeout
[INFO] 127.0.0.1:36422 - 797 "A IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.001029576s
[ERROR] plugin/errors: 2 pc-api.polestar.com. A: dial tcp 1.0.0.1:853: i/o timeout
[INFO] 127.0.0.1:42710 - 30848 "AAAA IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.001181723s
[ERROR] plugin/errors: 2 pc-api.polestar.com. AAAA: dial tcp 1.0.0.1:853: i/o timeout
[INFO] 127.0.0.1:39317 - 58075 "A IN pc-api.polestar.com. udp 48 true 2048" - - 0 30.001179835s
[ERROR] plugin/errors: 2 pc-api.polestar.com. A: dial tcp 1.0.0.1:853: i/o timeout

**Comment by jschlyter** [comment]
Have you removed your car from the integration and created a new one?

**Comment by wouterhardeman** [comment]
@jschlyter I think this is due to an update to the API done today. getConsumerCarsV2 is now under the `mystar-v2` endpoint and not in the `my-star` endpoint anymore.

**Comment by jschlyter** [comment]
I get correct responses for `getConsumerCarsV2` from both APIv1 and APIv2, so there's no harm moving to v2 only

**Comment by ZChenzy** [comment]
Hey man can you cut a tag please? I would love to use this integration and am being blocked by  the same login failure thank you :)

**Comment by jschlyter** [comment]
Will make a release as soon as #236 and #241 is reviewed and merged, should be today or tomorrow.

**Comment by jschlyter** [comment]
I've also made a pre-release available as https://github.com/pypolestar/polestar_api/releases/tag/1.10.0b1

**Comment by alexeckh** [comment]
@jschlyter : thanks for your support and work on that.
Pre-release 1.10.0b1 didn‘t work for me. Same error message.

**Comment by jschlyter** [comment]
With the pre-release version you can download diagnostics for the integration and, if you like, share with me via email and I'll take a look.

**Comment by alexeckh** [comment]
Sure, will do. 
How does it works when the integration can’t be installed? Pls advise

**Comment by jschlyter** [comment]
If a new device can't be created, enable debug logs and send me the logs.

**Comment by alexeckh** [comment]
ok have sent you a mail. Thanks!

**Comment by jlogan223** [comment]
Hi @jschlyter, thanks for developing this  integration. It's been working fine for me for the last few months, then a couple days ago, all sensors became unavailable. Tonight I deleted the integration, restarted HA, and now I get the same error mentioned above. 

On version 1.10.0.

Did this error ever get resolved?

Cheers

**Comment by jlogan223** [comment]
One other thing to add, I also have a MySkoda integration in HA and it seems it failed about the same time, now I can't seem to authenticate the app, the developer 
S think it could be down to the system polling the app too much and getting a temp ban l. I wonder if something has changed in HA that could be causing this behaviour for both apps? Just a thought

**Comment by jlogan223** [comment]
Error received when trying to add my vehicle.

This error originated from a custom integration.

Logger: custom_components.polestar_api.config_flow
Source: custom_components/polestar_api/config_flow.py:47
integration: Polestar API (documentation, issues)
First occurred: 19:19:06 (1 occurrences)
Last logged: 19:19:06

Unexpected error creating device
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/config_flow.py", line 47, in _create_device
    await device.async_init()
  File "/config/custom_components/polestar_api/polestar.py", line 143, in async_init
    await self.polestar_api.async_init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 67, in async_init
    if not (car_data := await self._get_vehicle_data(verbose=verbose)):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 269, in _get_vehicle_data
    raise PolestarNoDataException("No cars found in account")
custom_components.polestar_api.pypolestar.exception.PolestarNoDataException: No cars found in account

**Comment by howitzer84** [comment]
I too am having issues with the latest release. Everything has been working fine for a while and how the API will not authourise. 
Ive double checked my P*2 login and reinstalled the integration a couple of times to see if that may have been tripping it up. 

2024-12-10 15:59:37.508 ERROR (MainThread) [custom_components.polestar_api] Unexpected Error on update data cannot access local variable 'resumePath' where it is not associated with a value
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/__init__.py", line 34, in async_setup_entry
    await coordinator.async_init()
  File "/config/custom_components/polestar_api/polestar.py", line 143, in async_init
    await self.polestar_api.async_init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 61, in async_init
    await self.auth.get_token()
  File "/config/custom_components/polestar_api/pypolestar/auth.py", line 85, in get_token
    if (code := await self._get_code()) is None:
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/auth.py", line 140, in _get_code
    if resumePath is None:
       ^^^^^^^^^^

**Comment by jschlyter** [comment]
@howitzer84 please upgrade to the latest version and try again.

**Comment by howitzer84** [comment]
thanks, I just have through HACS and its up n' running again. Thanks for your continued dev support! :)

**Comment by jschlyter** [comment]
@alexeckh are you good? If so, please close the issue.

**Comment by alexeckh** [comment]
Hi Jakob,The issue persists with 1.10BestAlexander Von: Jakob Schlyter ***@***.***>Gesendet: Mittwoch, Dezember 11, 2024 9:37 AMAn: pypolestar/polestar_api ***@***.***>Cc: alexeckh ***@***.***>; Mention ***@***.***>Betreff: Re: [pypolestar/polestar_api] Unexpected error when creating the API -Polestar Account in the web works (Issue ***@***.*** are you good? If so, please close the issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.

**Comment by jlogan223** [comment]
I have updated to versions 1.11.0, and I seem to still have the same issues.

**Comment by leeyuentuen** [comment]
No car found could be the issue that there is no car linked on that account. Contact polestar to link them

**Comment by jlogan223** [comment]
> No car found could be the issue that there is no car linked on that account. Contact polestar to link them

I have had the app working for months, I have not changed anything on the polestar side, but now I get the error to initiate staying there is no car linked, but there definitely is.

**Comment by cnbleh** [comment]
Actually..

I lease the car, so didn't order it with my account. I figured the fact I am logged in via the app (with admin) meant it was in my account.

Sounds like there is an additional step to have it added to my account. Wonder if polestar will do it even if it's a lease. (I'll ask)

**Comment by jlogan223** [comment]
@jschlyter I think I saw on another similar issue that you mentioned it will be fixed with 1.12, when do you think this might be ready for release?

**Comment by jschlyter** [comment]
> @jschlyter I think I saw on another similar issue that you mentioned it will be fixed with 1.12, when do you think this might be ready for release?

I've just made a 1.12.0 a pre-release at https://github.com/pypolestar/polestar_api/releases/tag/1.12.0 - please test!

**Comment by jlogan223** [comment]
@jschlyter wow, I wasn't expecting a response on Christmas day, let lone a release. 💪.

I updated and same issue.

Getting error saying car is not in my account. I have been using your integration in my HA with this car for about 6 months. The car is on my App, something told me to check the polestar website, and for some reason the car is not in my account there. Seems all my issues are Polestars end, sorry I didn't think to check that before. No idea how I have access to my Car in the Polestar App, but on their website it says I have no cars. I will contact PS and see what's going on.

Thanks man.

Merry Christmas.

**Comment by BeauGiles** [comment]
> The car is on my App, something told me to check the polestar website, and for some reason the car is not in my account there. Seems all my issues are Polestars end, sorry I didn't think to check that before. No idea how I have access to my Car in the Polestar App, but on their website it says I have no cars. I will contact PS and see what's going on.

Yes, the pairing with the app on your phone is separate and doesn't necessarily need to be the same account, but only Polestar can add/fix missing cars from your account on the Polestar website.

**Comment by jlogan223** [comment]
@BeauGiles I
The car use to be in the polestar.com dashboard, I have had it working with this HA integration for months, but it seems PS have just deleted the car from my account for no reason.

**Comment by alexeckh** [comment]
Now with 1.12.0 i got the error 'Invalid username/password.' Log In at www.polestar.com works as expected (same credentials)

**Comment by jlogan223** [comment]
Turns out Polestar had deleted my car from my Dashboard, my app worked fine as they aren't connected, and the credential checking website still worked. Best to sign in to polestar.com and make sure your car is still showing in your dashboard.

________________________________

**Comment by jschlyter** [comment]
Any updates @alexeckh ?

**Comment by alexeckh** [comment]
Still the same issue with v 1.31
got the error 'Invalid username/password.' Log In at [www.polestar.com](http://www.polestar.com/) works as expected (same credentials)

**Comment by jschlyter** [comment]
> Still the same issue with v 1.31 got the error 'Invalid username/password.' Log In at [www.polestar.com](http://www.polestar.com/) works as expected (same credentials)

What country are you based in? When logging in are you redirected to `polestarid.eu.polestar.com` or something else?

**Comment by alexeckh** [comment]
Located in Germany. I’ll be redirected to https://polestarid.eu.polestar.com/

**Comment by alexeckh** [comment]
No special character. Only numbers and letters.

**Comment by jschlyter** [comment]
Please try https://github.com/pypolestar/polestar_api/releases/tag/1.14.0 and report back.

**Comment by alexeckh** [comment]
Issue persist with version 1.14.0

**Comment by jschlyter** [comment]
Perhaps you can try the instructions in https://github.com/pypolestar/polestar_api/issues/290#issuecomment-2620769226 and see if you can acquire more logs?

**Comment by alexeckh** [comment]
@jschlyter : with version 1.16.1 it now works. 
Thanks for your great work!
