### ISSUE TITLE
Integration refuses to start up

### ISSUE THREAD

**Issue by ccantill** [pypolestar/polestar_api#245]
In the logs I see:

```
Logger: custom_components.polestar_api
Source: custom_components/polestar_api/__init__.py:34
integration: Polestar API ([documentation](https://github.com/pypolestar/polestar_api), [issues](https://github.com/pypolestar/polestar_api/issues))
First occurred: 11:03:00 AM (2 occurrences)
Last logged: 11:13:38 AM

Unexpected Error on update data Client error '404 Not Found' for url 'https://pc-api.polestar.com/eu-north-1/my-star/' For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gql/transport/httpx.py", line 148, in _prepare_result
    result: Dict[str, Any] = response.json()
                             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I tried deleting my configuration and creating it again but it just fails with the same error during the setup.

**Comment by jschlyter** [comment]
Are you running the latest version of the component?

**Comment by ccantill** [comment]
HACS apparently didn't pick up the update. I forced a re-download and that pulled the latest version. Issue resolved. Thanks!

**Comment by skjeldgaard** [comment]
Great work - can confirm in now works!
