### ISSUE TITLE
Started getting an issue with the integration failing

### ISSUE THREAD

**Issue by Redding43** [pypolestar/polestar_api#246]
Started yesterday, have tried uninstalling and now won’t authenticate. API down?

This error originated from a custom integration.

Logger: custom_components.polestar_api
Source: custom_components/polestar_api/__init__.py:34
integration: Polestar API (documentation, issues)
First occurred: 13:11:23 (1 occurrences)
Last logged: 13:11:23

Unexpected Error on update data Client error '404 Not Found' for url 'https://pc-api.polestar.com/eu-north-1/my-star/' For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gql/transport/httpx.py", line 148, in _prepare_result
    result: Dict[str, Any] = response.json()
                             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 766, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/gql/transport/httpx.py", line 168, in _raise_response_error
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://pc-api.polestar.com/eu-north-1/my-star/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/polestar_api/__init__.py", line 34, in async_setup_entry
    await coordinator.async_init()
  File "/config/custom_components/polestar_api/polestar.py", line 150, in async_init
    await self.polestar_api.async_init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 69, in async_init
    if not (car_data := await self._get_vehicle_data(verbose=verbose)):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 204, in _get_vehicle_data
    result = await self._query_graph_ql(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 258, in _query_graph_ql
    raise exc
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 235, in _query_graph_ql
    result = await client.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gql/client.py", line 1628, in execute
    result = await self._execute(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gql/client.py", line 1537, in _execute
    result = await self.transport.execute(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gql/transport/httpx.py", line 293, in execute
    return self._prepare_result(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/gql/transport/httpx.py", line 151, in _prepare_result
    self._raise_response_error(response, "Not a JSON answer")
  File "/usr/local/lib/python3.12/site-packages/gql/transport/httpx.py", line 170, in _raise_response_error
    raise TransportServerError(str(e), e.response.status_code) from e
gql.transport.exceptions.TransportServerError: Client error '404 Not Found' for url 'https://pc-api.polestar.com/eu-north-1/my-star/'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

**Comment by Therealsipple** [comment]
The OAuth authentication is working properly and delivers the Access Token.
What failes is the access to the page 'https://pc-api.polestar.com/eu-north-1/my-star/' to request the VIN and some other data.
-> Response 404 - Page not found.

**Comment by Redding43** [comment]
Have just forced an upgrade to v1.10 and it appears to be ok now

**Comment by Therealsipple** [comment]
Solution: URL to get VIN etc. changed to 'https://pc-api.polestar.com/eu-north-1/mystar-v2/'
