### ISSUE TITLE
Polestar API fails to load

### ISSUE THREAD

**Issue by TapaniV** [pypolestar/polestar_api#265]
I noticed yesterday that the Polestar API wasn't working in my HA. I tried to reload it and got this in the log:
Logger: custom_components.polestar_api
Source: custom_components/polestar_api/__init__.py:34
integration: Polestar API ([documentation](https://github.com/pypolestar/polestar_api), [issues](https://github.com/pypolestar/polestar_api/issues))
First occurred: 07:09:34 (2 occurrences)
Last logged: 12:39:13

Unexpected Error on update data cannot access local variable 'resumePath' where it is not associated with a value
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/__init__.py", line 34, in async_setup_entry
    await coordinator.async_init()
  File "/config/custom_components/polestar_api/polestar.py", line 143, in async_init
    await self.polestar_api.async_init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 61, in async_init
    await self.auth.get_token()
  File "/config/custom_components/polestar_api/pypolestar/auth.py", line 85, in get_token
    if (code := await self._get_code()) is None:
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/auth.py", line 140, in _get_code
    if resumePath is None:
       ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'resumePath' where it is not associated with a value

Tried restarting HA, didn't help.

**Comment by motionist** [comment]
Update the Polestar api from HACS. Newest version world

**Comment by TapaniV** [comment]
Thanks. My HA didn't show the new version yet. Updating fixed the problem.
