### ISSUE TITLE
Integration Failed to setup error

### ISSUE THREAD

**Issue by vagy66** [pypolestar/polestar_api#266]
My integration has stopped working. 
Core 2024.12.2
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.7

Logger: custom_components.polestar_api
Source: custom_components/polestar_api/__init__.py:34
integration: Polestar API (documentation, issues)
First occurred: 11:36:32 (2 occurrences)
Last logged: 13:45:21

Unexpected Error on update data cannot access local variable 'resumePath' where it is not associated with a value
Traceback (most recent call last):
  File "/config/custom_components/polestar_api/__init__.py", line 34, in async_setup_entry
    await coordinator.async_init()
  File "/config/custom_components/polestar_api/polestar.py", line 143, in async_init
    await self.polestar_api.async_init()
  File "/config/custom_components/polestar_api/pypolestar/polestar.py", line 61, in async_init
    await self.auth.get_token()
  File "/config/custom_components/polestar_api/pypolestar/auth.py", line 85, in get_token
    if (code := await self._get_code()) is None:
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/pypolestar/auth.py", line 140, in _get_code
    if resumePath is None:
       ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'resumePath' where it is not associated with a value

**Comment by olalid** [comment]
See https://github.com/pypolestar/polestar_api/issues/265

**Comment by jschlyter** [comment]
Please test the current version and open a new issue if the problem persists.
